version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: calendar_db
      MYSQL_USER: calendar_user
      MYSQL_PASSWORD: calendar_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:

